name: Build and Test

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Install MKL
        run: sudo apt-get install -y libmkl-interface-dev libmkl-dev libclang-dev
      - name: Build
        run: |
          cp options.cmake.linux options.cmake
          cmake -B build
          cmake --build build
      - name: Pre-Generate
        run: |
          git submodule update --init
          nm -D /usr/lib/x86_64-linux-gnu/libmkl_intel_ilp64.so | grep " T " | awk '{ print $3; }' > data/list_ilp64
      - name: Generate
        run: |
          rm mklopenblas64.c
          cmake -B generate
          cmake --build generate
          ls -al
          head mklopenblas64.c


          
